### PR TITLE
Allow postgrex v0.17 and v0.18

### PR DESCRIPTION
**Pull request by mathiasose**
The same thing as #10 again, for the new `postgrex` released some days ago.

To me everything seems to be compatible, I have installed the package from the fork into our application and it seems to work just as before.

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
Hello @OvermindDL1,

Thanks for this package! Would it be possible to look at this PR?

**Comment by vheathen** [comment]
Hi @OvermindDL1 ,

thanks for the lib. Could you please have a look at this PR?
Thanks a lot!

**Comment by thbar** [comment]
I am considering forking for our project. Hopefully a merge & release can happen!

**Comment by OvermindDL1** [comment]
Oy, sorry for this delay.

Hmm, were there any api differences in these version, not in the part I'm using at least I think?  Do a more detailed check and release...

**Pull request merged**
